FORMAT: 1A
HOST: http://www.youraccountname.waxlrs.com

# Wax APIs
The resources described here are meant to provide analysis of the data submitted
via the core functionality of the Experience API as implemented by WaxLRS. This
includes analysis of information found in statements as well as information
found in the Document APIs.

## Questions?
We hope you find this documentation useful.
For any questions or feedback feel free to use the comments feature found in each HTTP method or contact us through our [support page]("http://saltbox.uservoice.com/").

## Group General Information
### Host
While Apiary lists the API host as `http://www.waxlrs.com/`, each of the endpoints below must include the main account in the url as follows:
`https://mainaccountname.waxlrs.com/`

### Authentication
Note that each of the examples below require the usage of basic authorization as part of the request.

## Group Common Error Responses
`400 Bad Request`
- "{your parameter} is not a legal JSON value, but is required to be":
In addition to checking for typos, make sure this isn't an empty value.

# Group Analyses

## Activity Popularity [/TCAPI/\_api/analyses/activity\_popularity{?descending}]
Activity Popularity allows you to determine the most and least popular
activities based on the number of the activity occurences.

### Activity Popularity Resource Attributes
The returned resource is a list of objects with the properties "key", "id", and
"value". "key" is the only important property.

+ key: list of four items:
    + index 0: Total number of statements with the given activity
    + index 1: Total number of unique agents
    + index 2: The activity id
    + index 3: The activity name

### Activity Popularity: Retrieval [GET]

+ Parameters

    + descending (optional, boolean) ... true for most popular and false for
    least popular

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        [
            {
                "key": [
                    1,
                    1,
                    "http://example.com/activity",
                    "Activity!"
                ],
                "id": "LDLmKDwePnetZy-vR-WaMZ",
                "value": null
            },
            {
                "key": [
                    1,
                    1,
                    "http://example.com/activity",
                    "Activity!"
                ],
                "id": "Ma6ShA3P86EY9qlYN__qnZ",
                "value": null
            }
        ]

## Basic Results [/TCAPI/\_api/analyses/basic_results{?activity}]
In order to store information about measured outcomes, the optional
["result" property](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#result)
is provided as part of an xAPI statement. While the value of this property
refers to one particular result for an agent, Basic Results provides all results
for a particular activity which is further organized by agent.

### Notes
Even though the xAPI standard has a "response" property within the "result"
property of an xAPI statement, we exclude it here and instead provide responses
separately in its own resource as seen below.

This resource provides information
to the "Results Summary" in the WaxLRS interface.

### Basic Results Resource Attributes
+ list of objects with the following properties:
    + key: list with the following items
        + index 0: agent
    + value: object with the following optional properties
        + scaled: list of scaled scores
        + raw: list of raw scores
        + completion: list of booleans indicating completion of activity
        + success: list of booleans indicating success in activity

### Basic Results: Retrieval [GET]

+ Parameters

    + activity (required, json, `http://example.com/activity/scoring`) ...
    xAPI activity id

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        [
            {
                "key": [{"mbox": "thisactivitywashard@example.com"}],
                "value": {
                    "completion": true,
                    "success": false
                }
            },
            {
                "key": [{"mbox": "irockedthis@example.com"}],
                "value": {
                    "completion": true,
                    "success": true
                }
            },
        ]

## Question Analysis [/TCAPI/\_api/analyses/questionanalysis{?activity}]
### Question Analysis: Retrieval [GET]

+ Parameters

    + activity (required, json, `http://example.com/activity/scoring`) ...
    xAPI activity id

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

## Responses [/TCAPI/\_api/analyses/responses{?activity}]
The "response" property is an optional property within the
["result" property](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#result)
which allows for arbitrary text appropriate to the activity to be recorded.
One example is a free response to an open ended survey question. The resource
provides information to the "Response Tabulation" in the WaxLRS interface.

### Responses Attributes
This resource returns a list of response objects with the following properties:

+ key: list of two items
    + index 0: agent
    + index 1: the timestamp of the response
+ value: the actual response text

### Responses: Retrieval [GET]

+ Parameters

    + activity (required, json, `http://example.com/activity/scoring`) ...
    xAPI activity id

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        [
            {
                "key": [
                    {"mbox": "iLoveBlueBooks@example.com"},
                    "2013-05-18T05:32:34.804Z"
                ],
                "value": "this is what i decided to write as my response"
            },
            {
                "key": [
                    {"mbox": "iHateBlueBooks@example.com"},
                    "2013-06-18T05:32:34.804Z"
                ],
                "value": "ah! writer's block!"
            },
        ]

## Scorechart [/TCAPI/\_api/analyses/scorechart{?activity}]
Like other referrences to 'score', scores correspond to the
[result.score property](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#result)
statement property. This resource provides a distribution of all scores for a
given activity. As expected, this Scorechart resource provides information to
the "Scorechart" report in the WaxLRS interface.

### Scorechart Resource Attributes
This resource returns an object with the following properties:

+ raw: object with raw scores and their total occurrences as key value pairs
+ scaled: object with scaled scores and their total occurrences as key value
pairs

### Scorechart: Retrieval [GET]

+ Parameters

    + activity (required, json, `http://example.com/activity/scoring`) ...
    xAPI activity id

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        {
          "raw": {},
          "scaled": {
            "0.3185880953164357": 1,
            "0.12008526250184093": 1,
            "0.9296901591327735": 1,
            "0.8510739693969134": 1
          }
        }

## Timeline [/TCAPI/\_api/analyses/timeline{?activity,agent,verb}]
The Timeline resource provides a way to find the number of occurrences for an
activity during various time frames.

### Timeline Resource Attributes
The resource returns a list of objects with the following properties:

+ key: a list in which each item corresponds to part of a single date
    + index 0: the year
    + index 1: the month
    + index 2: the day
+ value: the number of occurrences of this activity during the specified
time frame

### Timeline: Retrieval [GET]
#### Notes
Only one of the parameters below can be used.

+ Parameters

    + activity (optional, string, `http://example.com/activity/scoring`) ...
    xAPI activity id
    + agent (optional, json) ... xAPI agent object
    + verb (optional, string, `urn:verb:completed`) ... xAPI verb id

+ Parameters

    + activity (required, json, `http://example.com/activity/scoring`) ...
    xAPI activity id

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        [
            {
                "key": [
                    2012,
                    9,
                    12
                ],
                "value": 200
            },
            {
                "key": [
                    2013,
                    4,
                    22
                ],
                "value": 100
            }
        ]

## Verb Cloud [/TCAPI/\_api/analyses/verbcloud{?activity,agent}]
The Verb Cloud provides the total number of occurrences of verbs for the given
activity or agent.

### Verb Cloud Resource Attributes
This resource provides a list of objects with the following properties:

+ key: a list with one value, the verb id
+ value: an object with the following properties:
    + display: the verb's display property
    + total: the total number of the verb's occurrences

### Verb Cloud: Retrieval [GET]
#### Notes
Only one of the parameters below can be used.

+ Parameters

    + activity (optional, string, `http://example.com/activity/scoring`) ...
    xAPI activity id
    + agent (optional, json) ... xAPI agent object

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        [
            {
                "key": [
                    "urn:verb:completed"
                ],
                "value": {
                    "display": {},
                    "total": 2935
                }
            }
        ]

# Group Agent Mastery
## Agent Mastery [/TCAPI/\_api/agent\_mastery{?agent}]
???????????????
'Mastery' refers to the Saltbox Mastery Index (SMI) which summarizes an
individual's overall performance relative to peers. For example, an SMI score of 35%
indicates that the individual performed better than approximately 35% of the
individual's peers included in evaluation. Performance, in this case, refers to
achievement in scorable activities as found in the `result.score` property
of statements.

### Agent Mastery Resource Attributes
This resource returns an object with the following properties:

+ prediction: This is the SMI score formatted in decimals
+ stdev: The standard deviation
+ error: The error text if an error is present

### Agent Mastery: Retrieval [GET]

+ Parameters

    + agent (required, json, `{"mbox": "mailto:agent@example.com"}`) ...
    Agent object, as defined in xAPI, associated with this state

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        {
            "prediction": 0.55,
            "stdev": 0.25
        }

+ Response 200 (insufficient data)

        {
            "prediction": null,
            "stdev": null,
            "error": "Insufficient score data"
        }

# Group Agent Objects
## Agent Objects [/TCAPI/_api/agents{?agent}]
A list of full xAPI agents where 'full' means that an agent has the 'name'
property if a name was ever associated (via statements) with the agent's inverse
functional identifier (mbox, mbox_sha1sum, openid, account).

### TCAPI/_api/agents vs. TCAPI/agents
This resource, `TCAPI/_api/agents`, is different from our `TCAPI/agents`
resource which returns a list of Agent objects (regardless of being empty or
not) as opposed to being restricted to a single Person object. Among the
reasons you might use this resource is to retrieve the corresponding name for a
a list of agents when the only information you have is each agent's mbox
(email). #better example?

### Agent Objects: Retrieval [GET]
#### Notes
Assuming properly formed parameters, this resource will, in the very least,
return what you provide. For example, if you provide the agent parameter,
`{"mbox":"mailto:nonexistent@example.org"}`, even when this agent doesn't exist in
WaxLRS the response would still be:

        [
            {
                "mbox": "mailto:nonexistent@example.org"
            }
        ]

??? why do we do this again?

+ Parameters

    + agent (required, object, `{"mbox":"mailto:bauer@example.com"}`) ...
         One or more agent objects, as defined by xAPI, associated with this state.
         To request multiple agents in the query string:
         "agent={"mbox":"mailto:bauer@example.com"}&agent={"mbox":"mailto:almeida@example.com"}"

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        [
            {
                "mbox": "mailto:a28@example.org",
                "name": "Alejandro Argo"
            }
        ]

# Group Summary
## Summary [/TCAPI/_api/summary/{year}/{month}/{*period}]
The Summary resource is a helpful tool to find high-level information about
actors, verbs, activities, and statements within a specified time frame.

#### Notes
If at least one statement is found within the provided time frame,
an object with the following structure will be returned:

#### Summary Resource Attributes
This resource returns an object with the following properties:

+ new: Object with properties: verb, statement, actor, activity
    + verb: Total number of new verbs in time frame
    + actor: Total number of new actors in time frame
    + activity: Total number of new activities in time frame
    + statement: Total number of new statements in time frame
+ most_active: Object with properties: verb, actor, activity
    + verb: List of lists in which the inner lists contain:
        + An xAPI verb object
        + The number of occurrences for that verb within statements
    + actor: List of lists in which the inner lists contain:
        + An xAPI agent object
        + The number of occurrences for that verb within statements
    + activity: List of lists in which the inner lists contain:
        + An xAPI activity object
        + The number of occurrences for that activity within statements

If the specified time frame does not find any matching statements, the structure
will be as seen as it is displayed in the`Response 200 (no statements)` example
below.

### Summary: Retrieval [GET]
+ Parameters

    + year (required, number, `2013`) ...
    Retrieved information will have timestamps within this year
    + month (required, number, `9`) ...
    Retrieved information will have timestamps within this month
    + period (optional, numbers, `31/23/59/59`) ...
    Additional numbers that allow you to further narrow down the time frame for
    statements
    (e.g., `{day} / {hour}` or `{day} / {hour} /{minute} / {seconds})

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        {
            "new": {
                "verb": 2,
                "statement": 116,
                "actor": 2,
                "activity": 1
            },
            "most_active": {
                "verb": [
                    [
                        {
                            "id": "http://example.org/verbs#answered"
                        },
                        116
                    ],
                    [
                        {
                            "id": "http://adlnet.gov/expapi/verbs/completed"
                        },
                        17
                    ]
                ],
                "actor": [
                    [
                        {
                           "mbox": "mailto:xiao@example.com",
                           "name": "Xiao Xiao"
                        },
                        100
                    ],
                    [
                        {
                           "mbox": "mailto:somebodythatiusedtoknow@example.com",
                           "name": "Jasper Casper"
                        },
                        16
                    ]
                ],
                "activity": [
                    [
                        {
                           "definition": {
                              "name": {
                                 "en-US": "Swallow Lading and Airspeed Examination"
                              }
                           },
                           "id": "http://saltbox.com/tincan/examples/quiz",
                           "objectType": "Activity"
                        },
                        116
                    ]
                ]
            }
        }

+ Response 200 (no statements)

        {
            "new" {
                "statement": 0
            },
            "most_active": {}
        }

# Group Debug Documents
## Debug Documents [/TCAPI/_api/debug/documents]
### Debug Documents: Retrieval [GET]
This API is intended for internal use by Saltbox but is not restricted to
Saltbox.

Debug documents are the most recent (within 24 hours) documents stored by the
[Document APIs](http://docs.waxtcapi.apiary.io/#documentapis). This is useful
because the Document APIs cannot retrieve documents by timestamp alone. For
example, the
[Agent Profile API](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#agentprofapi)
requires an agent parameter when retrieving any
documents and then optionally the `since` parameter can be included. As such,
the debug documents provide the quickest access to recently stored documents.
This in turn allows you to perform any debugging related to documents if needed.

In the example below, one of the agent_profile documents has the id set to
"e12d6f90-2a3f-4b53-8ce5-d307e4c20f4b". Using this id and its corresponding
agent as parameters, you can use the
[Agent Profile API](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#agentprofapi)
to retrieve the specific document.

### Debug Document Attributes
As seen below, this resource returns an object with the single "documents"
property. Within this property's value, you can find a list of all the
documents that fall under the three different document types: agent profile,
activity profile, and state.

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        {
            "documents": {
                "agent_profile": [
                    {
                        "timestamp": "2014-02-18T23:31:08Z",
                        "document\_type": "agent_profile",
                        "identifier": "",
                        "agent": {
                            "mbox": "mailto:secret\_agent_man@example.com"
                        }
                    },
                    {
                        "timestamp": "2014-02-18T23:30:26Z",
                        "document\_type": "agent_profile",
                        "identifier": "e12d6f90-2a3f-4b53-8ce5-d307e4c20f4b",
                        "agent": {
                            "mbox": "mailto:agent_q@example.com"
                        }
                    }
                ],
                "activity_profile": [
                    {
                        "timestamp": "2014-02-18T23:31:05Z",
                        "document\_type": "activity_profile",
                        "identifier": "",
                        "activity_id": "urn:a:b"
                    },
                    {
                        "timestamp": "2014-02-18T23:30:24Z",
                        "document\_type": "activity_profile",
                        "identifier": "4dd3abfc-29b8-492f-a5e6-e72a7a9500de",
                        "activity_id": "urn:a:b"
                    }
                ],
                "state": [
                    {
                        "timestamp": "2014-02-18T23:31:26Z",
                        "activity_id": "http://example.com/activity",
                        "identifier": "1ee237p23e68114b9705e33912058a78",
                        "agent": {
                            "mbox": "mailto:lightningcatsho@example.com"
                        },
                        "document_type": "state"
                    },
                    {
                        "timestamp": "2014-02-18T23:31:23Z",
                        "activity_id": "http://example.com/activity",
                        "identifier": "94702a52b49341f0b3530a2e6fcd6555",
                        "agent": {
                            "mbox": "mailto:person@example.com"
                        },
                        "document_type": "state"
                    }
                ]
            }
        }

# Group Debug xAPI
## Debug xAPI [/TCAPI/_api/debug/xapi{?iterator,sequence}]
This API is intended for internal use by Saltbox but is not restricted to
Saltbox.

The Debug xAPI API allows you to retrieve the most recent (within 24 hours)
errors related to the various xAPI APIs (Statement and Document APIs).

## Debug xAPI: Retrieval [GET]
### Debug xAPI Resource Attributes

+ messages
    + status: the HTTP responsen code
    + received: timestamp of when the error occurred
    + parameters: an object of parameters sent as part of the request to the API
    + url: the API endpoint
    + explanation: The error message displayed to the API user, which is different than what is logged to Saltbox logging services
    + site: the site/account name of the person using this API
    + api: the name of the API being examined
    + verb: the HTTP verb
    + id: ?
+ iterator: The Amazon Kinesis iterator that iterates the stream of errors

### Notes
While this API can take the `iterator` and `sequence` parameters as described
below. These typically will not be needed and are set by Amazon.

+ Parameters

    + iterator (optional, string) ... Kinesis Iterator found by GET-ing this
    resource without parameters
    + sequence (optional, string) ... Sequence value found as a query parameter
    in the returned in the iterator url

+ Request

    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQZQ

+ Response 200

        {
            "messages": [
                {
                    "status": 400,
                    "received": "2014-02-21T18:50:09Z",
                    "parameters": {

                    },
                    "url": "http://youraccount.waxlrs.com/TCAPI/_api/mastery/agent",
                    "explanation": "Missing required parameters:\n                agent",
                    "site": "youraccount",
                    "api": "agent_mastery",
                    "verb": "GET",
                    "id": "fcegb2919b2811e3803f887529182736"
                },
                {
                    "status": 400,
                    "received": "2014-02-21T18:51:12Z",
                    "parameters": {

                    },
                    "url": "http://oneofyoursubaccounts.waxlrs.com/TCAPI/_api/mastery/agent",
                    "explanation": "Missing required parameters:\n                agent",
                    "site": "oneofyoursubaccounts",
                    "api": "agent_mastery",
                    "verb": "GET",
                    "id": "2291b99e9b2911e3a54c93028472812"
                }
            ],
            "iterator": "http://youraccount.waxlrs.com/TCAPI/_api/debug/xapi?iterator=longamazonkinesisiterator&sequence=sequencevalue"
        }
